# Generated by Django 4.2.5 on 2023-09-13 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default='1997-08-14'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.TextField(blank=True, default='none'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='firstName',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='lastName',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.TextField(blank=True, default='none'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_friends', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
