# Generated by Django 4.2.5 on 2024-03-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0014_alter_alert_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
